# Generated by Django 3.2.9 on 2021-11-04 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mise_a_jour', models.DateField(auto_now=True, verbose_name='Date de mise à jour')),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=150)),
                ('adresse', models.CharField(max_length=300)),
                ('code_postal', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='veillez entrer un code postal valide', regex='^[0-9]*$')])),
                ('ville', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='veillez entrer un numéro de téléphone valide', regex='[0-9]{10}')])),
                ('date_inscription', models.DateField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('commentaire', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
