# Generated by Django 3.2.9 on 2021-11-08 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_pour_animal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('date_mise_a_jour', models.DateField(auto_now=True, verbose_name='Date de mise à jour')),
                ('date_arrivee', models.DateField(blank=True, null=True, verbose_name='Date de première arrivée')),
                ('type_animal', models.CharField(choices=[('LAPIN', 'Lapin'), ('CHINCHILLA', 'Chinchilla'), ('COCHON_DINDE', "Cochon d'inde")], max_length=30, verbose_name="Type d'animal")),
                ('emplacement', models.CharField(choices=[('PENSION', 'Pension'), ('REFUGE', 'Refuge')], max_length=30, verbose_name='Emplacement')),
                ('sexe', models.CharField(choices=[('F', 'Féminin'), ('M', 'Masculin'), ('NI', 'Non Identifié')], max_length=30, verbose_name='Sexe')),
                ('sterilise', models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], max_length=30, verbose_name='Stérilisé')),
                ('vaccine', models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], max_length=30, verbose_name='Vacciné')),
                ('date_dernier_vaccin', models.DateField(blank=True, null=True, verbose_name='Date du dernier rappel de vaccin')),
                ('date_sterilisation', models.DateField(blank=True, null=True, verbose_name='Date de sterilisation')),
                ('inactif', models.BooleanField(default=False, verbose_name='Désactivé (Ne cocher que si vous ne souhaitez plus gérer cet animal dans l application) ')),
                ('description', models.CharField(blank=True, max_length=2000)),
                ('proprietaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hotel_pour_animal.personne', verbose_name='Propriétaire (à remplir uniquement si animal de la pension) ')),
            ],
        ),
    ]
